Update CMakeLists.txt for new peripheral detection logic
ESP-IDF 6.x (and prior) changed the way it resolves its components. This results in 2 file not found errors, where the files are still present but blanked out by the resolver.
/managed_components/zorxx__neopixel/neopixel.c:13:10: fatal error: driver/i2s_std.h: No such file or directory      
    #include "driver/i2s_std.h"
and #include "driver/i2s_common.h"
This commit changes it for both 'missing' files to be found again in ESP-IDF 6.0.
Tested with 5.5.4 and 6.0. Since other modules mentioned this change to be from <5.3 and resolved the issue with a dynamic switch i also added the same logic here. See espressif/onewire_bus managed component for that.